## YAML Template.
---
xsd2php:
  namespaces:
    'urn:OECD:StandardAuditFile-Tax:PT_1.04_01': 'Rebelo\SaftPt'
  destinations_php: 
#    'TestNs\MyApp': soap/src
    'Rebelo\SaftPt': src\Rebelo\SaftPt

  destinations_jms:
    'Rebelo\SaftPt': src\metadata
#    'TestNs\MyApp': soap\metadata  #  on Windows